algorithm: freematch
save_dir: ./saved_models/usb_cv/
save_name: freematch_rsscn_70_0_13
resume: true
load_path: ./saved_models/usb_cv//freematch_rsscn_70_0_13/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
batch_size: 32
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 70
uratio: 1
ema_m: 0.0
hard_label: true
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.001
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: wrn_28_2
net_from_name: false
data_dir: ./data
dataset: rsscn
train_sampler: RandomSampler
num_classes: 7
num_workers: 0
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: true
dist_url: tcp://127.0.0.1:10081
dist_backend: nccl
gpu: 0
use_pretrain: true
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/wrn_28_2_mlp_im_1k_32.pth
lambda_mcc: 1.0
use_mcc: false
lambda_rot: 1.0
use_rot: false
use_non_zero: false
weak_n: 1
strong_n: 3
delta: 0.001
test_model: 1